FROM ericyoungberg/postgis

RUN set -ex \
    ; \
    apt-get update -qq; \
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'; \
    apt-get install -y wget ca-certificates; \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - ; \
    apt-get update -qq \
    && apt-get install -y postgresql-9.5-pgrouting
