require "administrate/base_dashboard"

class SurveyResponseDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    survey: Field::BelongsTo,
    school: Field::HasOne,
    id: Field::Number,
    geometry: Field::String.with_options(searchable: false),
    question: Field::String,
    mode: Field::String,
    shed: Field::Number,
    distance: Field::Number.with_options(decimals: 2),
    grade_0: Field::String,
    to_school_0: Field::String,
    dropoff_0: Field::String,
    from_school_0: Field::String,
    pickup_0: Field::String,
    grade_1: Field::String,
    to_school_1: Field::String,
    dropoff_1: Field::String,
    from_school_1: Field::String,
    pickup_1: Field::String,
    grade_2: Field::String,
    to_school_2: Field::String,
    dropoff_2: Field::String,
    from_school_2: Field::String,
    pickup_2: Field::String,
    grade_3: Field::String,
    to_school_3: Field::String,
    dropoff_3: Field::String,
    from_school_3: Field::String,
    pickup_3: Field::String,
    grade_4: Field::String,
    to_school_4: Field::String,
    dropoff_4: Field::String,
    from_school_4: Field::String,
    pickup_4: Field::String,
    grade_5: Field::String,
    to_school_5: Field::String,
    dropoff_5: Field::String,
    from_school_5: Field::String,
    pickup_5: Field::String,
    grade_6: Field::String,
    to_school_6: Field::String,
    dropoff_6: Field::String,
    from_school_6: Field::String,
    pickup_6: Field::String,
    grade_7: Field::String,
    to_school_7: Field::String,
    dropoff_7: Field::String,
    from_school_7: Field::String,
    pickup_7: Field::String,
    grade_8: Field::String,
    to_school_8: Field::String,
    dropoff_8: Field::String,
    from_school_8: Field::String,
    pickup_8: Field::String,
    grade_9: Field::String,
    to_school_9: Field::String,
    dropoff_9: Field::String,
    from_school_9: Field::String,
    pickup_9: Field::String,
    grade_10: Field::String,
    to_school_10: Field::String,
    dropoff_10: Field::String,
    from_school_10: Field::String,
    pickup_10: Field::String,
    grade_11: Field::String,
    to_school_11: Field::String,
    dropoff_11: Field::String,
    from_school_11: Field::String,
    pickup_11: Field::String,
    grade_12: Field::String,
    to_school_12: Field::String,
    dropoff_12: Field::String,
    from_school_12: Field::String,
    pickup_12: Field::String,
    grade_13: Field::String,
    to_school_13: Field::String,
    dropoff_13: Field::String,
    from_school_13: Field::String,
    pickup_13: Field::String,
    grade_14: Field::String,
    to_school_14: Field::String,
    dropoff_14: Field::String,
    from_school_14: Field::String,
    pickup_14: Field::String,
    grade_15: Field::String,
    to_school_15: Field::String,
    dropoff_15: Field::String,
    from_school_15: Field::String,
    pickup_15: Field::String,
    grade_16: Field::String,
    to_school_16: Field::String,
    dropoff_16: Field::String,
    from_school_16: Field::String,
    pickup_16: Field::String,
    grade_17: Field::String,
    to_school_17: Field::String,
    dropoff_17: Field::String,
    from_school_17: Field::String,
    pickup_17: Field::String,
    grade_18: Field::String,
    to_school_18: Field::String,
    dropoff_18: Field::String,
    from_school_18: Field::String,
    pickup_18: Field::String,
    grade_19: Field::String,
    to_school_19: Field::String,
    dropoff_19: Field::String,
    from_school_19: Field::String,
    pickup_19: Field::String,
    nr_vehicles: Field::String,
    nr_licenses: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :created_at,
    :survey,
    :school
  ].freeze

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = [
    :survey,
    :school,
    :id,
    :question,
    :mode,
    :shed,
    :distance,
    :grade_0,
    :to_school_0,
    :dropoff_0,
    :from_school_0,
    :pickup_0,
    :grade_1,
    :to_school_1,
    :dropoff_1,
    :from_school_1,
    :pickup_1,
    :grade_2,
    :to_school_2,
    :dropoff_2,
    :from_school_2,
    :pickup_2,
    :grade_3,
    :to_school_3,
    :dropoff_3,
    :from_school_3,
    :pickup_3,
    :grade_4,
    :to_school_4,
    :dropoff_4,
    :from_school_4,
    :pickup_4,
    :grade_5,
    :to_school_5,
    :dropoff_5,
    :from_school_5,
    :pickup_5,
    :grade_6,
    :to_school_6,
    :dropoff_6,
    :from_school_6,
    :pickup_6,
    :grade_7,
    :to_school_7,
    :dropoff_7,
    :from_school_7,
    :pickup_7,
    :grade_8,
    :to_school_8,
    :dropoff_8,
    :from_school_8,
    :pickup_8,
    :grade_9,
    :to_school_9,
    :dropoff_9,
    :from_school_9,
    :pickup_9,
    :grade_10,
    :to_school_10,
    :dropoff_10,
    :from_school_10,
    :pickup_10,
    :grade_11,
    :to_school_11,
    :dropoff_11,
    :from_school_11,
    :pickup_11,
    :grade_12,
    :to_school_12,
    :dropoff_12,
    :from_school_12,
    :pickup_12,
    :grade_13,
    :to_school_13,
    :dropoff_13,
    :from_school_13,
    :pickup_13,
    :grade_14,
    :to_school_14,
    :dropoff_14,
    :from_school_14,
    :pickup_14,
    :grade_15,
    :to_school_15,
    :dropoff_15,
    :from_school_15,
    :pickup_15,
    :grade_16,
    :to_school_16,
    :dropoff_16,
    :from_school_16,
    :pickup_16,
    :grade_17,
    :to_school_17,
    :dropoff_17,
    :from_school_17,
    :pickup_17,
    :grade_18,
    :to_school_18,
    :dropoff_18,
    :from_school_18,
    :pickup_18,
    :grade_19,
    :to_school_19,
    :dropoff_19,
    :from_school_19,
    :pickup_19,
    :nr_vehicles,
    :nr_licenses,
    :created_at,
    :updated_at,
  ].freeze

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :survey,
    :school,
    :question,
    :mode,
    :shed,
    :distance,
    :grade_0,
    :to_school_0,
    :dropoff_0,
    :from_school_0,
    :pickup_0,
    :grade_1,
    :to_school_1,
    :dropoff_1,
    :from_school_1,
    :pickup_1,
    :grade_2,
    :to_school_2,
    :dropoff_2,
    :from_school_2,
    :pickup_2,
    :grade_3,
    :to_school_3,
    :dropoff_3,
    :from_school_3,
    :pickup_3,
    :grade_4,
    :to_school_4,
    :dropoff_4,
    :from_school_4,
    :pickup_4,
    :grade_5,
    :to_school_5,
    :dropoff_5,
    :from_school_5,
    :pickup_5,
    :grade_6,
    :to_school_6,
    :dropoff_6,
    :from_school_6,
    :pickup_6,
    :grade_7,
    :to_school_7,
    :dropoff_7,
    :from_school_7,
    :pickup_7,
    :grade_8,
    :to_school_8,
    :dropoff_8,
    :from_school_8,
    :pickup_8,
    :grade_9,
    :to_school_9,
    :dropoff_9,
    :from_school_9,
    :pickup_9,
    :grade_10,
    :to_school_10,
    :dropoff_10,
    :from_school_10,
    :pickup_10,
    :grade_11,
    :to_school_11,
    :dropoff_11,
    :from_school_11,
    :pickup_11,
    :grade_12,
    :to_school_12,
    :dropoff_12,
    :from_school_12,
    :pickup_12,
    :grade_13,
    :to_school_13,
    :dropoff_13,
    :from_school_13,
    :pickup_13,
    :grade_14,
    :to_school_14,
    :dropoff_14,
    :from_school_14,
    :pickup_14,
    :grade_15,
    :to_school_15,
    :dropoff_15,
    :from_school_15,
    :pickup_15,
    :grade_16,
    :to_school_16,
    :dropoff_16,
    :from_school_16,
    :pickup_16,
    :grade_17,
    :to_school_17,
    :dropoff_17,
    :from_school_17,
    :pickup_17,
    :grade_18,
    :to_school_18,
    :dropoff_18,
    :from_school_18,
    :pickup_18,
    :grade_19,
    :to_school_19,
    :dropoff_19,
    :from_school_19,
    :pickup_19,
    :nr_vehicles,
    :nr_licenses,
  ].freeze

  # Overwrite this method to customize how survey responses are displayed
  # across all pages of the admin dashboard.
  #
  # def display_resource(survey_response)
  #   "SurveyResponse ##{survey_response.id}"
  # end
end
